import { Language } from "./types";

const CROPS: Record<string, Record<Language, string>> = {
  Tomato: { te: "టమాటా", hi: "टमाटर", en: "Tomato" },
  Onion: { te: "ఉల్లిపాయ", hi: "प्याज", en: "Onion" },
  Chilli: { te: "మిరప", hi: "मिर्च", en: "Chilli" },
  Cotton: { te: "పత్తి", hi: "कपास", en: "Cotton" },
  Paddy: { te: "వరి", hi: "धान", en: "Paddy" },
  Maize: { te: "మొక్కజొన్న", hi: "मक्का", en: "Maize" },
};

export function cropLabel(crop: string, lang: Language): string {
  return CROPS[crop]?.[lang] || crop;
}

const COPY = {
  te: {
    appName: "కిసాన్ మిత్ర AI",
    appTagline: "మీ పంట · మీ ధర · మీ ఆదాయం",
    systemOk: "సేవ అందుబాటులో ఉంది",
    systemDown: "కనెక్షన్ లేదు — త్వరలో ప్రయత్నించండి",
    selectCrop: "పంట ఎంచుకోండి",
    heroTitle: "మీ పొలం నుండి మార్కెట్ వరకు",
    heroHighlight: "మీ కోసం AI సహాయం",
    heroSub: "పంట ఎప్పుడు కోయాలి, ఎక్కడ అమ్మాలి, ఎంత ధర — అన్నీ ఒక చోట",
    kpiIncome: "ఆదాయం పెరుగుదల",
    kpiLossSaved: "పంట నష్టం తగ్గింది",
    kpiTrust: "సలహా నమ్మకం",
    kpiDeals: "ఒప్పందాల విజయం",
    kpiTransport: "రవాణా సరిగ్గా",
    kpiFarmers: "రైతులకు సహాయం",
    yourField: "మీ పొలం సారాంశం",
    aiHelper: "మీ స్మార్ట్ కిసాన్ సహాయకుడు",
    acres: "ఎకరాలు",
    profitMore: "అదిక ఆదాయం",
    yourEarnings: "మీ సంపాదన",
    yourCrop: "మీ పంట",
    soilWet: "నేల తేమ",
    whenHarvest: "పంట కోత",
    daysLeft: "రోజులు మిగిలాయి",
    bestMarket: "ఉత్తమ మార్కెట్",
    perQuintal: "క్వింటాల్",
    weatherNews: "వాతావరణం",
    cropHealthMap: "పంట ఆరోగ్యం (ఉపగ్రహం నుండి)",
    healthGood: "ఆరోగ్య స్థితి",
    weakCrop: "బాగా లేదు",
    strongCrop: "చాలా బాగుంది",
    aiAdvice: "మీ కోసం సలహా",
    adviceTemplate: (crop: string, start: string, end: string, mandi: string) =>
      `మీ ${crop} ను ${start} నుండి ${end} మధ్య కోయండి. ${mandi} మార్కెట్ లో అమ్మితే ఎక్కువ ధర వస్తుంది. కోల్డ్ స్టోరేజ్ బుక్ చేసుకోండి — పంట చెడిపోదు.`,
    coldStorage: "చల్లని గోదాము",
    transport: "రవాణా",
    statusReady: "బుక్ చేయడానికి సిద్ధం",
    statusWaiting: "పంట కోత కోసం వేచి",
    oneClickTitle: "ఒకే బటన్ — పూర్తి సహాయం",
    oneClickSub: "పంట → ధర → గోదాము → అమ్మకం → రవాణా",
    runAll: "అన్నీ చూడండి",
    running: "సహాయం జరుగుతోంది...",
    dealTotal: "ఒప్పంద విలువ",
    youEarn: "మీ ఆదాయం",
    moreProfit: "ఎక్కువ లాభం",
    refNo: "రసీదు నంబరు",
    pipelineTitle: "మీ పంటకు సహాయం చేస్తున్న సేవలు",
    working: "పని చేస్తోంది...",
    done: "పూర్తి",
    waiting: "వేచి ఉంది",
    agents: {
      crop: "పంట ఎప్పుడు కోయాలి",
      price: "మండి ధర చూడండి",
      storage: "చల్లని గోదాము బుక్",
      deal: "కొనేవారితో ధర మాట్లాడండి",
      transport: "రవాణా ఏర్పాటు",
    },
    agentSteps: {
      crop: ["మీ పొలం సెన్సార్ల నుండి సమాచారం తీసుకుంటున్నాం", "ఉపగ్రహం నుండి పంట ఆరోగ్యం చూస్తున్నాం", "ఎప్పుడు కోయాలో లెక్కిస్తున్నాం"],
      price: ["మండి ధరలు చూస్తున్నాం", "గత సంవత్సరం ధరలు పోలుస్తున్నాం", "ఉత్తమ మార్కెట్ కనుగొంటున్నాం"],
      storage: ["సమీపంలో గోదాములు వెతుకుతున్నాం", "ఖాళీ ఉందో చూస్తున్నాం", "మీ కోసం బుక్ చేస్తున్నాం"],
      deal: ["కొనేవారిని వెతుకుతున్నాం", "మీకు మంచి ధర కోసం మాట్లాడుతున్నాం", "ఒప్పందం ముగిసింది"],
      transport: ["లారీ వెతుకుతున్నాం", "చౌకైన మార్గం ఎంచుకుంటున్నాం", "ట్రాకింగ్ లింక్ పంపుతాం"],
    },
    negotiateTitle: "మంచి ధర కోసం మాట్లాడుతాం",
    negotiateSub: "మీ బదులు AI కొనేవారితో మాట్లాడుతుంది",
    startNegotiate: "ధర మాట్లాడండి",
    negotiating: "మాట్లాడుతోంది...",
    round: "సారి",
    weTalk: "కిసాన్ మిత్ర",
    buyer: "కొనేవారు",
    dealDone: "ఒప్పందం అయింది!",
    moreThanTrader: "స్థానిక వ్యాపారి కంటే ఎక్కువ",
    youSaved: "మీకు ఆదా",
    negotiateHint: "బటన్ నొక్కండి — మీ కోసం ధర మాట్లాడుతాం",
    transportTitle: "మీ పంట ఎక్కడ ఉంది",
    transportSub: "లారీ మార్గం",
    arrivalTime: "ఎప్పుడు చేరుతుంది",
    distance: "దూరం",
    transportCost: "రవాణా ఖర్చు",
    stageFarm: "పొలం నుండి తీసుకోవడం",
    stageCold: "చల్లని గోదాము",
    stageBuyer: "కొనేవారి గోదాము",
    stageMarket: "మార్కెట్ కు",
    active: "ఇప్పుడు",
    ready: "సిద్ధం",
    pending: "వేచి",
    whatsappTitle: "వాట్సాప్ లో అడగండి",
    whatsappSub: "మాట్లాడండి లేదా టైప్ చేయండి — తెలుగు, హిందీ, ఇంగ్లీష్",
    mandiTitle: "ఈ రోజు మండి ధరలు",
    mandiSub: "మీ పంట ఎక్కడ ఎక్కువ ధర",
    mandi: "మండి",
    district: "జిల్లా",
    price: "ధర",
    trend: "పరిస్థితి",
    rising: "పెరుగుతోంది",
    falling: "తగ్గుతోంది",
    stable: "అలాగే ఉంది",
    loading: "లోడ్ అవుతోంది...",
    storyTitle: "మీ పంట ప్రయాణం",
    storySteps: ["🌾 పంట సిద్ధం", "📈 మండి ధర", "❄️ గోదాము", "🤝 అమ్మకం", "🚛 రవాణా", "💰 ఆదాయం"],
    footer: "కిసాన్ మిత్ర AI — భారతీయ రైతుల కోసం",
    backendError: "ఇంటర్నెట్ లేదు. కనెక్షన్ చూసి మళ్ళీ ప్రయత్నించండి.",
    waPlaceholder: "ఇక్కడ మీ ప్రశ్న రాయండి...",
    waHint: "మండి ధర, పంట కోత, అమ్మకం గురించి అడగండి",
    waTyping: "టైప్ చేస్తోంది...",
    waOnline: "ఆన్‌లైన్",
    waSpeak: "మాట్లాడండి",
    waListening: "వినుతున్నాం... మాట్లాడండి",
    waStopMic: "ఆపండి",
    waVoiceOn: "AI స్వరం ఆన్",
    waVoiceOff: "AI స్వరం ఆఫ్",
    waListenAgain: "మళ్ళీ వినండి",
    waMicHint: "🎤 మైక్ పట్టుకుని మాట్లాడండి — వదిలితే పంపబడుతుంది",
    waHoldToTalk: "పట్టుకుని మాట్లాడండి",
    waReleaseToSend: "వదిలితే పంపబడుతుంది",
    waMicDenied: "మైక్ అనుమతి ఇవ్వండి — సెట్టింగ్స్ లో చూడండి",
    waNoMic: "మైక్ లేదు — టైప్ చేయండి",
    waUseChrome: "Chrome లేదా Edge బ్రౌజర్ వాడండి",
    waNeedInternet: "వాయిస్ కోసం ఇంటర్నెట్ అవసరం — మళ్ళీ ప్రయత్నించండి",
    waTranscribing: "మీ మాటలు అర్థం చేసుకుంటున్నాం...",
    waHoldLonger: "కొంచెం సేపు పట్టుకుని మాట్లాడండి",
    waNoSpeech: "వినిపించలేదు — మళ్ళీ మాట్లాడండి",
    waSpeaking: "చెబుతున్నాం...",
    micConsentTitle: "మైక్ అనుమతి",
    micConsentBody: "మీరు మాట్లాడినప్పుడు మాత్రమే మైక్ వాడుతాం. AI సమాధానం వినడానికి స్వరం కూడా వాడుతాం.",
    micConsentAllow: "సరే, అనుమతిస్తాను",
    micConsentLater: "తర్వాత",
    loginTitle: "లాగిన్",
    loginSub: "మీ ఖాతాకు ప్రవేశించండి",
    signupTitle: "కొత్త ఖాతా",
    signupSub: "ఉచితంగా నమోదు చేసుకోండి",
    yourName: "మీ పేరు",
    yourPhone: "మొబైల్ నంబర్",
    yourVillage: "గ్రామం",
    yourDistrict: "జిల్లా",
    password: "పాస్వర్డ్",
    loginBtn: "లాగిన్",
    signupBtn: "నమోదు",
    logoutBtn: "లాగ్ అవుట్",
    noAccount: "ఖాతా లేదా?",
    hasAccount: "ఇప్పటికే ఖాతా ఉందా?",
    signupLink: "నమోదు చేయండి",
    loginLink: "లాగిన్",
    authError: "ఫోన్ లేదా పాస్వర్డ్ తప్పు",
    authExists: "ఈ నంబర్ ఇప్పటికే ఉంది",
    openAppTitle: "ఫోన్ లేదా లాప్టాప్ లో తెరవండి",
    openAppSub: "ఈ లింక్ ని షేర్ చేసి ఎక్కడైనా ఓపెన్ చేయండి",
    appLinkName: "యాప్ పేరు",
    websiteLink: "వెబ్‌సైట్ లింక్",
    openLaptop: "తెరవండి",
    copyLink: "లింక్ కాపీ",
    linkCopied: "కాపీ అయింది",
    scanQr: "ఫోన్ లో స్కాన్ చేయండి",
    phoneLink: "ఫోన్ లో ఓపెన్ చేయండి (ఈ లింక్)",
    laptopLink: "లాప్టాప్ లింక్",
    openPhone: "ఫోన్ లో తెరవండి",
    mobileStepsTitle: "ఫోన్ లో ఎలా తెరవాలి",
    mobileStep1: "లాప్టాప్ & ఫోన్ ఒకే WiFi లో ఉండాలి",
    mobileStep2: "ఫోన్ బ్రౌజర్ (Chrome) లో పై లింక్ టైప్ చేయండి లేదా QR స్కాన్ చేయండి",
    mobileStep3: "లాప్టాప్ లో npm run dev & backend 8001 పోర్ట్ రన్ అవుతుండాలి",
    hours: "గంటలు",
    km: "కి.మీ",
  },
  hi: {
    appName: "किसान मित्र AI",
    appTagline: "आपकी फसल · आपकी कीमत · आपकी कमाई",
    systemOk: "सेवा चालू है",
    systemDown: "कनेक्शन नहीं — बाद में कोशिश करें",
    selectCrop: "फसल चुनें",
    heroTitle: "खेत से मंडी तक",
    heroHighlight: "AI आपके साथ",
    heroSub: "कटाई कब करें, कहाँ बेचें, कितनी कीमत — सब एक जगह",
    kpiIncome: "आय में बढ़ोतरी",
    kpiLossSaved: "फसल बचत",
    kpiTrust: "सलाह पर भरोसा",
    kpiDeals: "सौदे सफल",
    kpiTransport: "ढुलाई ठीक",
    kpiFarmers: "किसानों की मदद",
    yourField: "आपके खेत का हाल",
    aiHelper: "आपका स्मार्ट किसान साथी",
    acres: "एकड़",
    profitMore: "ज़्यादा मुनाफा",
    yourEarnings: "आपकी कमाई",
    yourCrop: "आपकी फसल",
    soilWet: "मिट्टी की नमी",
    whenHarvest: "कटाई का समय",
    daysLeft: "दिन बाकी",
    bestMarket: "सबसे अच्छी मंडी",
    perQuintal: "क्विंटल",
    weatherNews: "मौसम",
    cropHealthMap: "फसल स्वास्थ्य (उपग्रह से)",
    healthGood: "स्वास्थ्य",
    weakCrop: "कमज़ोर",
    strongCrop: "बहुत अच्छी",
    aiAdvice: "आपके लिए सलाह",
    adviceTemplate: (crop: string, start: string, end: string, mandi: string) =>
      `${crop} को ${start} से ${end} के बीच काटें। ${mandi} मंडी में बेचने पर ज़्यादा कीमत मिलेगी। कोल्ड स्टोरेज बुक करें — फसल खराब नहीं होगी।`,
    coldStorage: "कोल्ड स्टोरेज",
    transport: "ढुलाई",
    statusReady: "बुक करने को तैयार",
    statusWaiting: "कटाई का इंतज़ार",
    oneClickTitle: "एक बटन — पूरी मदद",
    oneClickSub: "फसल → कीमत → गोदाम → बिक्री → ढुलाई",
    runAll: "सब देखें",
    running: "मदद हो रही है...",
    dealTotal: "सौदे की रकम",
    youEarn: "आपकी कमाई",
    moreProfit: "ज़्यादा फायदा",
    refNo: "रसीद नंबर",
    pipelineTitle: "आपकी फसल की मदद कर रही सेवाएँ",
    working: "काम कर रहा है...",
    done: "पूरा",
    waiting: "इंतज़ार",
    agents: {
      crop: "कटाई का समय",
      price: "मंडी भाव देखें",
      storage: "कोल्ड स्टोरेज बुक",
      deal: "खरीदार से बात",
      transport: "ढुलाई की व्यवस्था",
    },
    agentSteps: {
      crop: ["खेत के सेंसर से जानकारी ले रहे हैं", "उपग्रह से फसल देख रहे हैं", "कटाई का समय निकाल रहे हैं"],
      price: ["मंडी भाव देख रहे हैं", "पुराने भाव से तुलना", "सबसे अच्छी मंडी ढूँढ रहे हैं"],
      storage: ["पास के गोदाम देख रहे हैं", "खाली जगह चेक कर रहे हैं", "आपके लिए बुक कर रहे हैं"],
      deal: ["खरीदार ढूँढ रहे हैं", "आपके लिए कीमत पर बात कर रहे हैं", "सौदा हो गया"],
      transport: ["गाड़ी ढूँढ रहे हैं", "सस्ता रास्ता चुन रहे हैं", "ट्रैकिंग लिंक भेजेंगे"],
    },
    negotiateTitle: "अच्छी कीमत के लिए बातचीत",
    negotiateSub: "AI आपकी जगह खरीदार से बात करेगा",
    startNegotiate: "कीमत पर बात करें",
    negotiating: "बात हो रही है...",
    round: "राउंड",
    weTalk: "किसान मित्र",
    buyer: "खरीदार",
    dealDone: "सौदा हो गया!",
    moreThanTrader: "स्थानीय व्यापारी से ज़्यादा",
    youSaved: "आपकी बचत",
    negotiateHint: "बटन दबाएँ — आपके लिए कीमत तय करेंगे",
    transportTitle: "आपकी फसल कहाँ है",
    transportSub: "गाड़ी का रास्ता",
    arrivalTime: "कब पहुँचेगी",
    distance: "दूरी",
    transportCost: "ढुलाई खर्च",
    stageFarm: "खेत से उठाना",
    stageCold: "कोल्ड स्टोरेज",
    stageBuyer: "खरीदार के गोदाम",
    stageMarket: "मंडी तक",
    active: "अभी",
    ready: "तैयार",
    pending: "बाकी",
    whatsappTitle: "व्हाट्सऐप पर पूछें",
    whatsappSub: "बोलें या लिखें — हिंदी, तेलुगु, अंग्रेज़ी",
    mandiTitle: "आज के मंडी भाव",
    mandiSub: "आपकी फसल कहाँ महँगी बिकेगी",
    mandi: "मंडी",
    district: "ज़िला",
    price: "भाव",
    trend: "हालत",
    rising: "बढ़ रहा",
    falling: "घट रहा",
    stable: "जैसा था",
    loading: "लोड हो रहा है...",
    storyTitle: "आपकी फसल का सफ़र",
    storySteps: ["🌾 फसल तैयार", "📈 मंडी भाव", "❄️ गोदाम", "🤝 बिक्री", "🚛 ढुलाई", "💰 कमाई"],
    footer: "किसान मित्र AI — भारतीय किसानों के लिए",
    backendError: "इंटरनेट नहीं है। कनेक्शन देखकर फिर कोशिश करें।",
    waPlaceholder: "यहाँ अपना सवाल लिखें...",
    waHint: "मंडी भाव, कटाई, बिक्री के बारे में पूछें",
    waTyping: "लिख रहा है...",
    waOnline: "ऑनलाइन",
    waSpeak: "बोलें",
    waListening: "सुन रहे हैं... बोलिए",
    waStopMic: "रोकें",
    waVoiceOn: "AI आवाज़ चालू",
    waVoiceOff: "AI आवाज़ बंद",
    waListenAgain: "फिर सुनें",
    waMicHint: "🎤 माइक दबाकर बोलें — छोड़ने पर भेजा जाएगा",
    waHoldToTalk: "दबाकर बोलें",
    waReleaseToSend: "छोड़ने पर भेजें",
    waMicDenied: "माइक की अनुमति दें — सेटिंग में जाएँ",
    waNoMic: "माइक नहीं — टाइप करें",
    waUseChrome: "Chrome या Edge ब्राउज़र इस्तेमाल करें",
    waNeedInternet: "आवाज़ के लिए इंटरनेट चाहिए — फिर कोशिश करें",
    waTranscribing: "आपकी बात समझ रहे हैं...",
    waHoldLonger: "थोड़ी देर दबाकर बोलें",
    waNoSpeech: "सुनाई नहीं दिया — फिर बोलें",
    waSpeaking: "बोल रहे हैं...",
    micConsentTitle: "माइक की अनुमति",
    micConsentBody: "माइक सिर्फ बोलने के लिए। AI जवाब सुनने के लिए आवाज़ भी इस्तेमाल होगी।",
    micConsentAllow: "हाँ, अनुमति दें",
    micConsentLater: "बाद में",
    loginTitle: "लॉगिन",
    loginSub: "अपने खाते में आएँ",
    signupTitle: "नया खाता",
    signupSub: "मुफ़्त में जुड़ें",
    yourName: "आपका नाम",
    yourPhone: "मोबाइल नंबर",
    yourVillage: "गाँव",
    yourDistrict: "ज़िला",
    password: "पासवर्ड",
    loginBtn: "लॉगिन",
    signupBtn: "जुड़ें",
    logoutBtn: "लॉग आउट",
    noAccount: "खाता नहीं है?",
    hasAccount: "पहले से खाता है?",
    signupLink: "जुड़ें",
    loginLink: "लॉगिन",
    authError: "फ़ोन या पासवर्ड गलत",
    authExists: "यह नंबर पहले से है",
    openAppTitle: "फ़ोन या लैपटॉप पर खोलें",
    openAppSub: "लिंक शेयर करके कहीं भी खोलें",
    appLinkName: "ऐप का नाम",
    websiteLink: "वेबसाइट लिंक",
    openLaptop: "खोलें",
    copyLink: "लिंक कॉपी",
    linkCopied: "कॉपी हो गया",
    scanQr: "फ़ोन से स्कैन करें",
    phoneLink: "फ़ोन पर खोलें (यह लिंक)",
    laptopLink: "लैपटॉप लिंक",
    openPhone: "फ़ोन पर खोलें",
    mobileStepsTitle: "फ़ोन पर कैसे खोलें",
    mobileStep1: "लैपटॉप और फ़ोन एक ही WiFi पर हों",
    mobileStep2: "फ़ोन के Chrome में ऊपर लिंक टाइप करें या QR स्कैन करें",
    mobileStep3: "लैपटॉप पर npm run dev और backend पोर्ट 8001 चालू हो",
    hours: "घंटे",
    km: "किमी",
  },
  en: {
    appName: "KisanMitra",
    appTagline: "Your crop · Your price · Your income",
    systemOk: "Service is ready",
    systemDown: "No connection — try again",
    selectCrop: "Choose crop",
    heroTitle: "From your field to the market",
    heroHighlight: "AI helps you earn more",
    heroSub: "When to harvest, where to sell, best price — all in one place",
    kpiIncome: "More income",
    kpiLossSaved: "Crop saved",
    kpiTrust: "Advice you can trust",
    kpiDeals: "Deals done",
    kpiTransport: "Transport ready",
    kpiFarmers: "Farmers helped",
    yourField: "Your field today",
    aiHelper: "Your smart farming friend",
    acres: "acres",
    profitMore: "extra profit",
    yourEarnings: "Your earnings",
    yourCrop: "Your crop",
    soilWet: "soil moisture",
    whenHarvest: "Harvest in",
    daysLeft: "days left",
    bestMarket: "Best market",
    perQuintal: "per quintal",
    weatherNews: "Weather",
    cropHealthMap: "How healthy is your crop",
    healthGood: "Health score",
    weakCrop: "Needs care",
    strongCrop: "Very healthy",
    aiAdvice: "Advice for you",
    adviceTemplate: (crop: string, start: string, end: string, mandi: string) =>
      `Harvest your ${crop} between ${start} and ${end}. Sell at ${mandi} market for the best price. Book cold storage so your crop does not spoil.`,
    coldStorage: "Cold storage",
    transport: "Transport",
    statusReady: "Ready to book",
    statusWaiting: "Waiting for harvest",
    oneClickTitle: "One button — full help",
    oneClickSub: "Crop → Price → Storage → Sale → Transport",
    runAll: "Show me everything",
    running: "Working for you...",
    dealTotal: "Deal amount",
    youEarn: "You earn",
    moreProfit: "more profit",
    refNo: "Receipt no.",
    pipelineTitle: "Services helping your crop",
    working: "Working...",
    done: "Done",
    waiting: "Waiting",
    agents: {
      crop: "When to harvest",
      price: "Check mandi prices",
      storage: "Book cold storage",
      deal: "Talk to buyer",
      transport: "Arrange transport",
    },
    agentSteps: {
      crop: ["Reading your field sensors", "Checking crop health from satellite", "Calculating best harvest date"],
      price: ["Checking mandi prices", "Comparing last year's rates", "Finding best market for you"],
      storage: ["Looking for nearby cold storage", "Checking if space is free", "Booking for you"],
      deal: ["Finding buyers", "Negotiating a better price for you", "Deal done"],
      transport: ["Finding a truck", "Choosing cheapest route", "Sending tracking link"],
    },
    negotiateTitle: "We negotiate a better price",
    negotiateSub: "AI talks to the buyer on your behalf",
    startNegotiate: "Get better price",
    negotiating: "Talking...",
    round: "Round",
    weTalk: "KisanMitra",
    buyer: "Buyer",
    dealDone: "Deal done!",
    moreThanTrader: "more than local trader",
    youSaved: "You saved",
    negotiateHint: "Press the button — we will negotiate for you",
    transportTitle: "Where is your crop",
    transportSub: "Truck route",
    arrivalTime: "Arrives in",
    distance: "Distance",
    transportCost: "Transport cost",
    stageFarm: "Pickup from farm",
    stageCold: "Cold storage",
    stageBuyer: "Buyer warehouse",
    stageMarket: "To market",
    active: "Now",
    ready: "Ready",
    pending: "Later",
    whatsappTitle: "Ask on WhatsApp",
    whatsappSub: "Speak or type — Telugu, Hindi, English",
    mandiTitle: "Today's mandi prices",
    mandiSub: "Where your crop sells for more",
    mandi: "Market",
    district: "District",
    price: "Price",
    trend: "Trend",
    rising: "Going up",
    falling: "Going down",
    stable: "Same as before",
    loading: "Loading...",
    storyTitle: "Your crop's journey",
    storySteps: ["🌾 Crop ready", "📈 Mandi price", "❄️ Storage", "🤝 Sold", "🚛 On the way", "💰 You earn"],
    footer: "KisanMitra AI — for Indian farmers",
    backendError: "No internet. Check connection and try again.",
    waPlaceholder: "Type your question here...",
    waHint: "Ask about mandi price, harvest, or selling",
    waTyping: "typing...",
    waOnline: "online",
    waSpeak: "Speak",
    waListening: "Listening... speak now",
    waStopMic: "Stop",
    waVoiceOn: "AI voice on",
    waVoiceOff: "AI voice off",
    waListenAgain: "Listen again",
    waMicHint: "🎤 Hold mic and speak — release to send",
    waHoldToTalk: "Hold to talk",
    waReleaseToSend: "Release to send",
    waMicDenied: "Allow microphone in browser settings",
    waNoMic: "No mic — type your question",
    waUseChrome: "Use Chrome or Edge browser for voice",
    waNeedInternet: "Internet needed for voice — try again",
    waTranscribing: "Understanding your words...",
    waHoldLonger: "Hold a little longer while speaking",
    waNoSpeech: "Could not hear you — try again",
    waSpeaking: "Speaking...",
    micConsentTitle: "Microphone permission",
    micConsentBody: "We only use the mic when you hold to talk. AI replies can be read aloud.",
    micConsentAllow: "Yes, allow",
    micConsentLater: "Not now",
    loginTitle: "Login",
    loginSub: "Sign in to your account",
    signupTitle: "Create account",
    signupSub: "Join free in one minute",
    yourName: "Your name",
    yourPhone: "Mobile number",
    yourVillage: "Village",
    yourDistrict: "District",
    password: "Password",
    loginBtn: "Login",
    signupBtn: "Sign up",
    logoutBtn: "Log out",
    noAccount: "No account?",
    hasAccount: "Already have an account?",
    signupLink: "Sign up",
    loginLink: "Login",
    authError: "Wrong phone or password",
    authExists: "This number is already registered",
    openAppTitle: "Open on phone or laptop",
    openAppSub: "Share this link to open anywhere",
    appLinkName: "App name",
    websiteLink: "Website link",
    openLaptop: "Open",
    copyLink: "Copy link",
    linkCopied: "Copied",
    scanQr: "Scan on phone",
    phoneLink: "Open on phone (this link)",
    laptopLink: "Laptop link",
    openPhone: "Open on phone",
    mobileStepsTitle: "How to open on phone",
    mobileStep1: "Laptop and phone must be on the same WiFi",
    mobileStep2: "Type the link above in phone Chrome or scan the QR code",
    mobileStep3: "Keep npm run dev and backend on port 8001 running on laptop",
    hours: "hours",
    km: "km",
  },
} as const;

export function formatReceiptNo(id: string): string {
  const clean = id.replace(/[^0-9A-Za-z]/g, "").toUpperCase();
  return clean.length >= 6 ? clean.slice(0, 6) : clean.padStart(6, "0");
}

export type FarmerCopy = (typeof COPY)[Language];

export function useFarmerCopy(lang: Language): FarmerCopy {
  return COPY[lang];
}

export const AGENT_KEYS = ["crop", "price", "storage", "deal", "transport"] as const;

export const AGENT_BACKEND_NAMES = [
  "Crop Readiness Agent",
  "Price Intelligence Agent",
  "Cold Storage Agent",
  "Buyer Negotiation Agent",
  "Logistics Coordinator Agent",
];
